Groep8DotNetProjectenII/Groep8DotNetProjectenII/ViewModels/KlimatogrammenViewModels.cs
using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNet.Highcharts;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Options;
using Groep8DotNetProjectenII.Models.Domain;

namespace Groep8DotNetProjectenII.ViewModels
{
    public class KlimatogrammenIndexViewModel
    {
        public IList<Continent> Continenten { get; set; }

        [Display(Name = "Selecteer werelddeel")]
        public int ContinentId { get; set; }

        public IList<Land> Landen { get; set; }
        [Display(Name = "Selecteer land")]
        public int LandId { get; set; }
        public IList<Locatie> Weerstations { get; set; }
        [Display(Name = "Selecteer weerstation")]
        public int WeerstationId { get; set; }

        public KlimatogrammenIndexViewModel(IList<Continent> continenten)
        {
            this.Continenten = continenten;

        }

        public KlimatogrammenIndexViewModel()
        {

        }
    }

    public class KlimatogramTonenViewModel
    {
        public int WeerstationId { get; set; }
        public Highcharts Chart { get; set; }
        public ICollection<int> Neerslagen { get; set; }
        public ICollection<double> Temperaturen { get; set; }
        public int BeginJaar { get; set; }
        public int EindJaar { get; set; }
        public double GemiddeldeJaarTemperatuur { get; set; }
        public int SomJaarNeerslag { get; set; }
        public bool Selecteren { get; set; }

        public KlimatogramTonenViewModel(Locatie l, bool selecteren = true)
        {
            Selecteren = selecteren;
            Neerslagen      = new List<int>();
            Temperaturen    = new List<double>();
            
            WeerstationId   = l.WeerstationNummer;
            EindJaar        = l.Klimatogram.EindDatum;
            BeginJaar       = l.Klimatogram.BeginDatum;
            
            GemiddeldeJaarTemperatuur = l.Klimatogram.GemmideldeJaarTemperatuur;
            SomJaarNeerslag = l.Klimatogram.SomJaarNeerslag;

            for (int i = 0; i < Enum.GetValues(typeof(Maanden)).Length; i++)
            {
                double ctmp = l.Klimatogram.Maanden.ElementAt(i).GemTmp;
                int cnrslg = l.Klimatogram.Maanden.ElementAt(i).GemNslg;
                Neerslagen.Add(cnrslg);
                Temperaturen.Add(ctmp);
            }


            double maxTmp = Temperaturen.Max(t => t);
            double minTmp = Temperaturen.Min(t => t);
            double maxNsl = Neerslagen.Max(t => t);

            int maxTmpAfg = (int) (maxTmp + (10 - maxTmp%10));
            int minTmpAfg = (int) (minTmp - (10 + minTmp%10));
            int maxNslAfg = (int) (maxNsl + (10 - maxNsl%10));

            YAxis neerslagAxis = new YAxis
            {
                Max = maxNsl / 2 > maxTmp ? maxNslAfg : 2 * maxTmpAfg,
                Min = minTmp > 0 ? 0 : minTmpAfg * 2,
                TickInterval = 10,
                Labels = new YAxisLabels
                {
                    Formatter = "function() { return this.value >= 0 ? this.value : ''; }",
                    
                    Style = "color: '#89A54E'"
                },
                Title = new YAxisTitle
                {
                    Text = "Neerslag (mm)",
                    Style = "color: '#89A54E'"
                }
            };

            YAxis tempAxis = new YAxis()
            {

                Max = maxNsl / 2> maxTmp ? maxNslAfg / 2 : maxTmpAfg,
                Min = minTmp > 0 ? 0 : minTmpAfg,
                TickInterval = 5,
                Labels = new YAxisLabels
                {
                    Formatter = "function() { return this.value ; }",
                    Style = "color: '#4572A7'"
                },
                Title = new YAxisTitle
                {
                    Text = "Temperatuur (°C)",
                    Style = "color: '#4572A7'"
                },
                Opposite = true
            };

            //tempAxis.TickInterval = neerslagAxis.TickInterval / 2;
            int[] longitude = l.GeeLongitudeGradenMinutenSeconden();
            int[] latitude = l.GeefLatitudeGradenMinutenSeconden();

            var chart = new Highcharts("chart")
                    .SetTitle(new Title() { Text = String.Format("{0} ({1}) - {2}", l.Naam, l.Land.Naam, WeerstationId)})
                    .SetSubtitle(
                        new Subtitle() { 
                            Text = String.Format("Latitude: {0}° {1}&apos; N Longitude: {2}° {3}&apos; W",
                            latitude[0], latitude[1], longitude[0], longitude[1]), UseHTML = true
                        }
                    )
                    .SetXAxis(new XAxis
                    {
                        Categories =
                            new[] { "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D" }
                    })
                    .SetYAxis(new[]
                {
                    neerslagAxis,tempAxis
                   
                })
                    .SetSeries(new[]
                {
                    new Series
                    {
                        Name    = "Neerslag (mm)",
                        Type    = ChartTypes.Column,
                        Color   = ColorTranslator.FromHtml("#0141B0"),
                        Data    = new Data(Neerslagen.Cast<object>().ToArray())
                    },
                    new Series
                    {
                        Name    = "Temperatuur (°C)",
                        Type    = ChartTypes.Line,
                        YAxis   = "1",
                        Color   = ColorTranslator.FromHtml("#FF0303"),
                        Data    = new Data(Temperaturen.Cast<object>().ToArray())
                    }
                });
            
            Chart = chart;
        }

        public KlimatogramTonenViewModel()
        {
            
        }


    }

}

Groep8DotNetProjectenII/Groep8DotNetProjectenII/Controllers/KlimatogrammenController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Groep8DotNetProjectenII.Models.Domain;
using Groep8DotNetProjectenII.ViewModels;
using WebGrease.Css.Extensions;

namespace Groep8DotNetProjectenII.Controllers
{
    public class KlimatogrammenController : Controller
    {
        private IContinentRepository continentenRepository;
        private ILandRepository landenRepository;
        private IKlimatogramRepository klimatogramRepository;
        private ILocatieRepository locatieRepository;

        public KlimatogrammenController(IContinentRepository continentenRepository, ILandRepository landenRepository, IKlimatogramRepository klimatogramRepository, ILocatieRepository locatieRepository)
        {
            this.continentenRepository = continentenRepository;
            this.landenRepository = landenRepository;
            this.klimatogramRepository = klimatogramRepository;
            this.locatieRepository = locatieRepository;
        }

        public ActionResult Index(Leerjaar leerjaar)
        {
            if (ModelState.IsValid)
            {
                    List<Continent> continenten = continentenRepository.PerJaar(leerjaar).ToList();
                    KlimatogrammenIndexViewModel kivm = new KlimatogrammenIndexViewModel(continenten);

                    return View(kivm);   
            }
            else
            {
                TempData["Error"] = "Gelieve eerst een leerjaar te selecteren";
                return RedirectToAction("Index", "Oefeningen");
            }
            
            
        }

        [HttpPost]
        public ActionResult SelecteerLand(KlimatogrammenIndexViewModel kivm)
        {

            Continent c = continentenRepository.FindById(kivm.ContinentId);
            if (c!= null )
                kivm.Landen = c.Landen.OrderBy(l=>l.Naam).ToList();
            return PartialView("_LandSelecteren", kivm);
        }

        [HttpPost]
        public ActionResult SelecteerWeerstation(KlimatogrammenIndexViewModel kivm)
        {

            Land l = landenRepository.FindById(kivm.LandId);
            if (l!=null && l.Locaties.Count == 0)
            {
                TempData["Message"] = "Het land heeft geen klimatogrammen";

            }
            kivm.Weerstations = l.Locaties.OrderBy(w => w.Naam).ToList();

            return PartialView("_WeerstationSelecteren", kivm);
        }

        [HttpPost]
        public ActionResult MaakKlimatogram(KlimatogramTonenViewModel ktvm)
        {
           
            Locatie l = locatieRepository.FindById(ktvm.WeerstationId);
            if (l != null)                
                ktvm = new KlimatogramTonenViewModel(l);

            return PartialView("_KlimatogramTonen", ktvm);
        }

        public ActionResult VerwijderSessie(Leerjaar jaar)
        {
            jaar.Verwijder();
            return RedirectToAction("Index", "Oefeningen");
        }

    }

}

Groep8DotNetProjectenII/Groep8DotNetProjectenII/Views/Klimatogrammen/Index.cshtml
@using Groep8DotNetProjectenII.Models.Domain
@model Groep8DotNetProjectenII.ViewModels.KlimatogrammenIndexViewModel


@{
    ViewBag.Title = "Index";
}

<h2>Selecteer Klimatogram</h2>

@Html.ActionLink("Terug naar selecteer leerjaar", "VerwijderSessie")

<hr/>
<div id="continenten">
    @{ Html.RenderPartial("_ContinentSelecteren", Model);}
</div>
<div id="landen">
    @{Html.RenderPartial("_LandSelecteren", Model);}
</div>
<div id="weerstations">
    @{ Html.RenderPartial("_WeerstationSelecteren", Model); }
</div>

<div id="klimatogram">

</div>

Groep8DotNetProjectenII/Groep8DotNetProjectenII/Views/Klimatogrammen/_ContinentSelecteren.cshtml
@model Groep8DotNetProjectenII.ViewModels.KlimatogrammenIndexViewModel

@using (Ajax.BeginForm("SelecteerLand", "Klimatogrammen", new AjaxOptions()
{
    UpdateTargetId = "landen",
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "POST"
}))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ContinentId, new { @class = "col-md-2 control-label" })
        <div class="dropdown">
            @Html.DropDownListFor(m => m.ContinentId, new SelectList(Model.Continenten, "ContinentId", "Naam"), "--selecteer werelddeel--", new { @class = "form-control" })
        </div>
    </div>
}

<script type="text/javascript">


    $('#ContinentId').change(function () {
        $("#weerstations select").empty();
        $(this).parents('form').submit();
    });

</script>

Groep8DotNetProjectenII/Groep8DotNetProjectenII/Views/Klimatogrammen/_LandSelecteren.cshtml
@model Groep8DotNetProjectenII.ViewModels.KlimatogrammenIndexViewModel

@if (Model.Landen != null && Model.Landen.Count > 0)
{

    using (Ajax.BeginForm("SelecteerWeerstation", "Klimatogrammen", new AjaxOptions()
    {
        UpdateTargetId = "weerstations",
    }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.LandId, new { @class = "col-md-2 control-label" })
            <div class="dropdown">
                @Html.DropDownListFor(m => m.LandId, new SelectList(Model.Landen, "LandId", "Naam"), "--selecteer land--", new { @class = "form-control" })
            </div>

        </div>
    }
}

else
{
   
    <div class="form-group">
        @Html.LabelFor(m => m.LandId, new { @class = "col-md-2 control-label" })
        <div class="dropdown">

            <select class="form-control"></select>

        </div>

    </div>
}

<script type="text/javascript">
    $('#LandId').change(function () {
        $(this).parents('form').submit();
    });
</script>  

Groep8DotNetProjectenII/Groep8DotNetProjectenII/Views/Klimatogrammen/_WeerstationSelecteren.cshtml
@model Groep8DotNetProjectenII.ViewModels.KlimatogrammenIndexViewModel

@if (Model.Weerstations != null && Model.Weerstations.Count > 0)
{
    using (Ajax.BeginForm("MaakKlimatogram", "Klimatogrammen", new AjaxOptions()
    {
        UpdateTargetId = "klimatogram",
    }))
    {

        <div class="form-group">
            @Html.LabelFor(m => m.WeerstationId, new { @class = "col-md-2 control-label" })
            <div class="dropdown">
                @Html.DropDownListFor(m => m.WeerstationId, new SelectList(Model.Weerstations, "WeerstationNummer", "Naam"), "--Selecteer weerstation--", new { @class = "form-control" })
            </div>
        </div>





    }
}

else
{
    if(TempData["Message"] != null)
    {
        <div class="alert alert-danger col-md-offset-2" role="alert">
            @TempData["Message"]
        </div>
    }
    <div class="form-group">
        @Html.LabelFor(m => m.WeerstationId, new { @class = "col-md-2 control-label" })
        
        
        <div class="dropdown">

            <select class="form-control"></select>
        </div>
    </div>


}

<script type="text/javascript">
    $('#WeerstationId').change(function () {
        $("#klimatogram").html("" +
            "<div class=\"jumbotron\">" +
            "<div class=\"progress progress-striped active\">"
            + "<div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"100\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width : 100%\"></div>"
            + "</div></div>");
        $(this).parents('form').submit();
    });
</script>