Groep8DotNetProjectenII/Groep8DotNetProjectenII/Controllers/VragenController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using DeterminerenTest.Models.Domein;
using Groep8DotNetProjectenII.Models.Domain;
using Groep8DotNetProjectenII.ViewModels;
using WebGrease.Css.Extensions;

namespace Groep8DotNetProjectenII.Controllers
{
    public class VragenController : Controller
    {
        private IGradenRepository gradenRepository;
        private ILocatieRepository locatieRepository;

        public VragenController(IGradenRepository gradenRepository, ILocatieRepository locatieRepository)
        {
            this.gradenRepository = gradenRepository;
            this.locatieRepository = locatieRepository;
        }

        public VragenController()
        {
            
        }

        public ActionResult Index(Leerjaar leerjaar, int klimatogramId = -1)
        {
            if (ModelState.IsValid && klimatogramId != -1)
            {
                int graad = leerjaar.LeerjaarNaarGraad();
                VragenLijst vragenlijst = gradenRepository.FindByGraadNummer(graad).VragenLijst;
                if (vragenlijst == null)
                {
                    return RedirectToAction("Index", "Determineren", new {klimatogramId = klimatogramId});
                }
                Locatie l = locatieRepository.FindById(klimatogramId);

                List<ParameterViewModel> parameterViewModels =
                    vragenlijst.Vragen.Select(p => new ParameterViewModel(p, l.Klimatogram)).ToList();
                VragenViewModel vvm = new VragenViewModel(parameterViewModels, new KlimatogramTonenViewModel(l, false), l.Klimatogram.KlimatogramId);

                return View(vvm);
            }
            TempData["Error"] = "Gelieve eerst een leerjaar te selecteren";
            return RedirectToAction("Index", "Oefeningen");
        }

        [HttpPost, ActionName("Controleer")]
        public ActionResult Index(Leerjaar leerjaar, [Bind(Prefix = "Pvm")]List<ParameterViewModel> antwoord, int klimatogramId)
        {
            Locatie l = locatieRepository.FindById(klimatogramId);
            if (ModelState.IsValid)
            {
                try
                {
                    VragenLijst vr = gradenRepository.FindByGraadNummer(leerjaar.LeerjaarNaarGraad()).VragenLijst;
                   
                    var isJuist = vr.controleerAntwoorden(antwoord.Select(a => a.Antwoord).ToList(),l.Klimatogram);
                    int positie=0;
                    
                    for (int i = 0; i < antwoord.Count; i++)
                    {
                        antwoord[i] = new ParameterViewModel(vr.Vragen.FirstOrDefault(p => p.Beschrijving == antwoord[i].Vraag), l.Klimatogram);
                        antwoord[i].Correct = isJuist[i];
                    }

                    if(antwoord.Count(a => !a.Correct)>0)
                        throw new Exception("Gelieve volgende vragen opnieuw te beantwoorden");

                    TempData["Message"] = "U heeft de vragen correct beantwoord";
                    return RedirectToAction("Index", "Determineren", new { klimatogramId = klimatogramId });
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            return View("Index", new VragenViewModel(antwoord,new KlimatogramTonenViewModel(l, false), l.Klimatogram.KlimatogramId ));
        }
    }
}

Groep8DotNetProjectenII/Groep8DotNetProjectenII/Views/Shared/_KlimatogramTonen.cshtml
@using System.Activities.Statements
@using System.Diagnostics.Eventing.Reader
@model Groep8DotNetProjectenII.ViewModels.KlimatogramTonenViewModel
@if(@Model.Chart != null){

    if (Model.Selecteren)
    {
        <hr/>
        @:<div class="jumbotron">
    }
        
    <div>
        @Model.Chart
    </div>
    <div class="table-responsive">
        <table class="table text-right">
            <thead>
                <tr>
                    <th class="text-right"></th>
                    <th class="text-right">J</th>
                    <th class="text-right">f</th>
                    <th class="text-right">M</th>
                    <th class="text-right">A</th>
                    <th class="text-right">M</th>
                    <th class="text-right">J</th>
                    <th class="text-right">J</th>
                    <th class="text-right">A</th>
                    <th class="text-right">S</th>
                    <th class="text-right">O</th>
                    <th class="text-right">N</th>
                    <th class="text-right">D</th>
                    <th class="text-right">Jaar</th>
                </tr>
            </thead>
            <tbody>
                <tr>

                    <th>N (mm)</th>
                    @foreach (int neerslag in Model.Neerslagen)
                    {
                        <td>@neerslag</td>
                    }
                    <td>@Model.SomJaarNeerslag</td>
                </tr>
                <tr>
                    <th>T (°C)</th>
                    @foreach (double temperaturen in Model.Temperaturen)
                    {
                        <td>@String.Format("{0:.0}", temperaturen)</td>
                    }
                    <td>@Model.GemiddeldeJaarTemperatuur</td>
                </tr>
            </tbody>
        </table>
        <p style="text-align: center">Klimatologische gemiddelden @Model.BeginJaar - @Model.EindJaar</p>

    </div>
    if (Model.Selecteren){
        using(Html.BeginForm("Index", "Vragen", new{klimatogramId = Model.WeerstationId})){
        
            <div class="form-group">
                <div class="col-md-11">
                    <input type="submit" class="btn btn-primary" style="margin-bottom:10px;" value="Selecteer klimatogram"/>
                </div>
            </div>
        }
        @:</div>
    }




}

Groep8DotNetProjectenII/Groep8DotNetProjectenII/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HoGent project Klimatogrammen</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/unobtrusive")
    @Scripts.Render("~/bundles/highcharts")
    @RenderSection("scripts", required: false)
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Klimatogrammen", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Oefenen", "Index", "Oefeningen")</li>
            </ul>
        </div>
    </div>
</div>
    <div id="fluid-content" class="container-fluid">
    </div>
    <div class="container body-content">
        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger alert-dismissable" role="alert" style="margin-top: 10px">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
                @TempData["Error"]
            </div>
        }
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-success alert-dismissable" role="alert" style="margin-top: 10px">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
                @TempData["Message"]
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HoGent project klimatogrammen</p>
        </footer>
    </div>

</body>
</html>